In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib widget
import os, sys, getpass
user = getpass.getuser()
sys.path.append(f'/home/{user}/codes/hpe_library/')
from lib_import import *
from my_utils import *
os.chdir('/home/hrai/codes/MotionBERT')

In [2]:
root_3dhp = '/home/hrai/Datasets/HAAI/3DHP'
source = 'posynda' # 
test_data_path = os.path.join(root_3dhp, source, 'data_test_3dhp_ori.npz')
test_data = np.load(test_data_path, allow_pickle=True)['data'].item()

In [36]:
save_folder = '/home/hrai/codes/MotionBERT/data/motion3d/3dhp_gt_test_pkl'
if not os.path.exists(save_folder):
    os.makedirs(save_folder)

subject_list = test_data.keys()
for subject in subject_list:
    data = {}
    for key in ['joint_2d', 'confidence', 'camera_name', 'action', 'source', 'frame', 'cam_3d']:
        data[key] = []

    #print(test_data[subject].keys())
    joint_2d = mpi_inf_3dhp2h36m(test_data[subject]['data_2d'])
    cam_3d = mpi_inf_3dhp2h36m(test_data[subject]['data_3d'])
    print(joint_2d.shape, cam_3d.shape)
    print(cam_3d[0])
    frame_num = [i for i in range(joint_2d.shape[0])]
    source = [subject]*len(frame_num)
    action = [subject]*len(frame_num)
    camera_id = [subject]*len(frame_num)

    # store
    data['joint_2d'] = np.array(joint_2d).copy()
    data['confidence'] = np.ones([len(joint_2d), 17, 1])
    data['camera_name'] = np.array(camera_id).copy()
    data['action'] = np.array(action).copy()
    data['source'] = np.array(source).copy()
    data['frame'] = np.array(frame_num).copy()
    data['cam_3d'] = np.array(cam_3d).copy()

    file_name = subject + '.pkl'
    save_path = os.path.join(save_folder, file_name)
    savepkl(data, save_path)

(6151, 17, 2) (6151, 17, 3)
[[-2.36576000e+01 -3.12547000e+02  3.19737000e+03]
 [-1.60364150e+02 -3.12185500e+02  3.17301000e+03]
 [-1.76980000e+02  2.32113000e+02  3.30704000e+03]
 [-2.00960000e+02  6.06866000e+02  3.51300000e+03]
 [ 1.13048950e+02 -3.12908500e+02  3.22173000e+03]
 [ 8.74982000e+01  2.36966000e+02  3.33383000e+03]
 [ 7.08552000e+01  6.27805000e+02  3.50819000e+03]
 [-1.96031591e+01 -5.73096014e+02  3.16997891e+03]
 [-1.10505000e+01 -8.62998000e+02  3.11869000e+03]
 [-3.24063000e+00 -9.51798000e+02  3.07407000e+03]
 [ 8.53552000e+00 -1.14001000e+03  3.00919000e+03]
 [ 1.47484000e+02 -8.00602000e+02  3.14221000e+03]
 [ 4.89966000e+02 -8.00759000e+02  3.14245000e+03]
 [ 7.45976000e+02 -8.30479000e+02  3.11360000e+03]
 [-1.64029000e+02 -8.03324000e+02  3.11882000e+03]
 [-5.05514000e+02 -8.27772000e+02  3.12803000e+03]
 [-7.61073000e+02 -8.29655000e+02  3.08396000e+03]]
(6080, 17, 2) (6080, 17, 3)
[[ 165.438       -85.9934     2411.6       ]
 [  32.5707      -85.358225   2