In [1]:
import os
import torch
import torch.nn as nn

# os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
# os.environ["CUDA_VISIBLE_DEVICES"]= "0, 1"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print('Device:', device)  # 출력결과: cuda 
print('Count of using GPUs:', torch.cuda.device_count())   #출력결과: 1 (GPU #2 한개 사용하므로)
print('Current cuda device:', torch.cuda.current_device())  # 출력결과: 2 (GPU #2 의미)

Device: cuda
Count of using GPUs: 2
Current cuda device: 0


In [2]:
import os
import torch

os.environ["NCCL_P2P_DISABLE"]= '1'

v = torch.randn(5, device='cuda:0')
print(v)
print(v.to('cuda:1'))
print(v.to('cpu').to('cuda:1'))

tensor([ 0.2949, -0.9822, -1.4375, -0.4219,  0.2653], device='cuda:0')
tensor([ 0.2949, -0.9822, -1.4375, -0.4219,  0.2653], device='cuda:1')
tensor([ 0.2949, -0.9822, -1.4375, -0.4219,  0.2653], device='cuda:1')
